/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner.index'
import { Route as AuthenticatedOwnerCategoriesRouteImport } from './routes/_authenticated/owner.categories'
import { Route as AuthenticatedOwnerProductsRouteImport } from './routes/_authenticated/owner.products'
import { Route as AuthenticatedOwnerShortagesRouteImport } from './routes/_authenticated/owner.shortages'
import { Route as AuthenticatedSellerIndexRouteImport } from './routes/_authenticated/seller.index'
import { Route as AuthenticatedSellerPosRouteImport } from './routes/_authenticated/seller.pos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedOwnerCategoriesRoute =
  AuthenticatedOwnerCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerProductsRoute =
  AuthenticatedOwnerProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerShortagesRoute =
  AuthenticatedOwnerShortagesRouteImport.update({
    id: '/shortages',
    path: '/shortages',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedSellerIndexRoute =
  AuthenticatedSellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerPosRoute = AuthenticatedSellerPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedSellerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/owner/categories': typeof AuthenticatedOwnerCategoriesRoute
  '/owner/products': typeof AuthenticatedOwnerProductsRoute
  '/owner/shortages': typeof AuthenticatedOwnerShortagesRoute
  '/seller/pos': typeof AuthenticatedSellerPosRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
  '/seller/': typeof AuthenticatedSellerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owner/categories': typeof AuthenticatedOwnerCategoriesRoute
  '/owner/products': typeof AuthenticatedOwnerProductsRoute
  '/owner/shortages': typeof AuthenticatedOwnerShortagesRoute
  '/seller/pos': typeof AuthenticatedSellerPosRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
  '/seller': typeof AuthenticatedSellerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/_authenticated/owner/categories': typeof AuthenticatedOwnerCategoriesRoute
  '/_authenticated/owner/products': typeof AuthenticatedOwnerProductsRoute
  '/_authenticated/owner/shortages': typeof AuthenticatedOwnerShortagesRoute
  '/_authenticated/seller/pos': typeof AuthenticatedSellerPosRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
  '/_authenticated/seller/': typeof AuthenticatedSellerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner'
    | '/seller'
    | '/owner/categories'
    | '/owner/products'
    | '/owner/shortages'
    | '/seller/pos'
    | '/owner/'
    | '/seller/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/owner/categories'
    | '/owner/products'
    | '/owner/shortages'
    | '/seller/pos'
    | '/owner'
    | '/seller'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/owner'
    | '/_authenticated/seller'
    | '/_authenticated/owner/categories'
    | '/_authenticated/owner/products'
    | '/_authenticated/owner/shortages'
    | '/_authenticated/seller/pos'
    | '/_authenticated/owner/'
    | '/_authenticated/seller/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/categories': {
      id: '/_authenticated/owner/categories'
      path: '/categories'
      fullPath: '/owner/categories'
      preLoaderRoute: typeof AuthenticatedOwnerCategoriesRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/products': {
      id: '/_authenticated/owner/products'
      path: '/products'
      fullPath: '/owner/products'
      preLoaderRoute: typeof AuthenticatedOwnerProductsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/shortages': {
      id: '/_authenticated/owner/shortages'
      path: '/shortages'
      fullPath: '/owner/shortages'
      preLoaderRoute: typeof AuthenticatedOwnerShortagesRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/seller/': {
      id: '/_authenticated/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof AuthenticatedSellerIndexRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/pos': {
      id: '/_authenticated/seller/pos'
      path: '/pos'
      fullPath: '/seller/pos'
      preLoaderRoute: typeof AuthenticatedSellerPosRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
  }
}

interface AuthenticatedOwnerRouteChildren {
  AuthenticatedOwnerCategoriesRoute: typeof AuthenticatedOwnerCategoriesRoute
  AuthenticatedOwnerProductsRoute: typeof AuthenticatedOwnerProductsRoute
  AuthenticatedOwnerShortagesRoute: typeof AuthenticatedOwnerShortagesRoute
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
}

const AuthenticatedOwnerRouteChildren: AuthenticatedOwnerRouteChildren = {
  AuthenticatedOwnerCategoriesRoute: AuthenticatedOwnerCategoriesRoute,
  AuthenticatedOwnerProductsRoute: AuthenticatedOwnerProductsRoute,
  AuthenticatedOwnerShortagesRoute: AuthenticatedOwnerShortagesRoute,
  AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
}

const AuthenticatedOwnerRouteWithChildren =
  AuthenticatedOwnerRoute._addFileChildren(AuthenticatedOwnerRouteChildren)

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerPosRoute: typeof AuthenticatedSellerPosRoute
  AuthenticatedSellerIndexRoute: typeof AuthenticatedSellerIndexRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerPosRoute: AuthenticatedSellerPosRoute,
  AuthenticatedSellerIndexRoute: AuthenticatedSellerIndexRoute,
}

const AuthenticatedSellerRouteWithChildren =
  AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRouteWithChildren
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOwnerRoute: AuthenticatedOwnerRouteWithChildren,
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
